title: <p align="center"> Satyanarayana k</p>
logo: img/pic.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/kalluri-satyanarayana-429156110/">LinkedIn</a> |
  <a href="https://github.com/satyanarayana25">GitHub</a>
  
  <br>   
  I'm Learning Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.i am learning from upgrad
  Working in Cognizant for 3 years.
  <br>
  </p>

theme: jekyll-theme-minimal
